### ISSUE TITLE
Error with :validation_option

### ISSUE THREAD

**Issue by MatthieuSegret** [Ethelo/kronky#2]
Hi,

I have this validation rule in my model : 
`validate_length(:content, min: 30)`

I have a error if `options { key, value}` is present in my mutation query : 
`mutation {
    createRecipe(title: "a title", content: "less than 30") {
    result {
      id,
      title
    },
    messages {
      template,
      options {
        key,
        value
      }
    }
  }
}`

The error is : 
`** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: {:count, 30}
        (elixir) lib/map.ex:424: Map.get({:count, 30}, :key, nil)
        (absinthe) lib/absinthe/middleware/map_get.ex:9: Absinthe.Middleware.MapGet.call/2`

I think there is a type error with `options` resolution. Do you have an idea ?

**Comment by yordis** [comment]
@MatthieuSegret the issue is that you need to convert those https://github.com/Ethelo/kronky/blob/master/lib/kronky/changeset_parser.ex#L54 options into a list some map for be able to work

**Comment by yordis** [comment]
@MatthieuSegret the issue is that you need to convert those https://github.com/Ethelo/kronky/blob/master/lib/kronky/changeset_parser.ex#L54 options into a list some map for be able to work ***with the default absinthe resolver for `field`***

The following example is the approach I took to resolve this issue.

For example: 
```
object :error_metadata do
    field :key, :string do
      resolve &MetadataResolver.key/3 # < ---- don't need it by there is some concerns on why I had to do it anyway, check the code base
    end
    field :value, :string do
      resolve &MetadataResolver.value/3  # < ---- don't need it by there is some concerns on why I had to do it anyway, check the code base
    end
  end

  object :error do
    field :metadata, list_of(:metadata) # <----- Notice it's an list of error metadata
  end
```

The `error map` have a serialized value of metadata. [check code here](https://github.com/straw-hat-team/straw_hat/blob/ca693ec2e6fda3a5a3105d9dc372ca51a1403400/lib/straw_hat/error/error_metadata.ex#L38)
```
def new(key, value) do
    %ErrorMetadata{
      key: to_string(key),
      value: to_string(value)}
end
def serialize(metadata), do: Enum.map(metadata, fn({key, value}) -> new(key, value) end)
```

So because I convert the `options` in this case to some list of map I can do what you are trying to do.  [check code here](https://github.com/straw-hat-team/straw_hat/blob/ca693ec2e6fda3a5a3105d9dc372ca51a1403400/lib/straw_hat/error.ex#L55)

Does that makes sense?

Full code on: https://github.com/straw-hat-team/straw_hat_graphql/blob/7c1763708277e330bd1dc52bd09d6cb228e2e86d/lib/straw_hat_graphql/types.ex#L45

100% credit to this repo on the parser ❤️

**Comment by yordis** [comment]
@MatthieuSegret but also understand what Absinthe is trying.

Look the error
```
 Map.get({:count, 30}, :key, nil)
```
That is because when you do `field` Absinthe just setup some resolver that do at the end of the day `Map.get` on the field name, which is `key` in this case. 

What you could also do without running into my application design is to setup a different resolver like I did [here](https://github.com/straw-hat-team/straw_hat/blob/ca693ec2e6fda3a5a3105d9dc372ca51a1403400/lib/straw_hat/graphql/types.ex#L30) and there resolver will just look for the tuple position whenever is `key` or `value` of what you are looking for

```
defmodule OptionsResolver do
  def key({key, _value}, _args, _resolution),  do: {:ok, key}
  def value({_key, value}, _args, _resolution), do: {:ok, value}
end
```

**Comment by lauraannwilliams** [comment]
Thanks for helping out on this @yordis !
